In [2]:
import numpy as np
from datascience import *
import warnings
warnings.simplefilter('ignore', FutureWarning)

/Users/kaiser/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [4]:
import math
weird_numbers = make_array("-2", math.floor(17.6), "3", 5 ** math.ceil(5.3))
weird_numbers

array(['-2', '17', '3', '15625'],
      dtype='<U21')

In [8]:
book_title_words = make_array("Eats", "Shoots", "and Leaves")
book_title_words

array(['Eats', 'Shoots', 'and Leaves'],
      dtype='<U10')

In [9]:
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


### Indexing Arrays

In [10]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers[2]
third_element

-6

In [11]:
blank_a = "third"
blank_b = "fourth"
blank_c = 0
blank_d = 3
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

In [32]:
arr = list(range(142))
index_of_last_element = arr[-1]
index_of_last_element

141

In [38]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')
president_birth_years

array([1732, 1735, 1743, 1751, 1758, 1767, 1767, 1773, 1782, 1784, 1790,
       1791, 1795, 1800, 1804, 1808, 1809, 1822, 1822, 1829, 1831, 1833,
       1837, 1843, 1856, 1857, 1858, 1865, 1872, 1874, 1882, 1884, 1890,
       1908, 1911, 1913, 1913, 1917])

In [34]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')
most_recent_birth_year = president_birth_years[-1]
most_recent_birth_year

1917

In [36]:
min_of_birth_years = min(president_birth_years)
min_of_birth_years

1732

### Basic Array Arithmetic

In [39]:
first_product = 42 * 157
second_product = -4224 * 157
third_product = 424224242 * 157
fourth_product = 250 * 157
print("First Product:", first_product)
print("Second Product:", second_product)
print("Third Product:", third_product)
print("Fourth Product:", fourth_product)

First Product: 6594
Second Product: -663168
Third Product: 66603205994
Fourth Product: 39250


In [41]:
numbers = make_array(42, -4224, 424224242, 250)
products = numbers * 157
products

array([       6594,     -663168, 66603205994,       39250])

In [46]:
correct_products = numbers * 1577
correct_products

array([       66234,     -6661248, 669001629634,       394250])

In [49]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")
max_temperatures_celisus = (max_temperatures - 32) * 5 / 9
celsius_temps_rounded = np.round(max_temperatures_celisus)
celsius_temps_rounded

array([ -4.,  31.,  32., ...,  17.,  23.,  16.])

In [51]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")
min_temperatures_celius = (min_temperatures - 32) * 5 / 9
celsius_temperature_ranges = max_temperatures_celisus - min_temperatures_celius
celsius_temperature_ranges

array([  6.66666667,  10.        ,  12.22222222, ...,  17.22222222,
        11.66666667,  11.11111111])

### Old Faithful

In [53]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')
shortest = min(waiting_times)
longest = max(waiting_times)
average = np.mean(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70.8970588235 minutes on average.


In [56]:
differences = np.diff(waiting_times)
biggest_decrease = max(differences)
biggest_decrease

47

In [67]:
faithful = Table.read_table('old_faithful.csv').drop("eruptions")
faithful_with_eruption_nums = faithful.with_column("eruption number", np.arange(faithful.num_rows) + 1).select(1, 0)
first_nine_waiting_times = faithful_with_eruption_nums["waiting"].take(range(9))
total_waiting_time_until_tenth = sum(first_nine_waiting_times)
total_waiting_time_until_tenth

633

In [72]:
differences = np.diff(waiting_times)
# np.abs(differences)
average_error = np.mean(np.abs(differences))
average_error

20.520295202952031

### Tables

In [74]:
from datascience import Table
fruits = Table().with_columns(
    "fruit name", ["apples", "oranges", "pinapples"],
    "amount", [4, 3, 3]
)
fruits

fruit name | amount
apples     | 4
oranges    | 3
pinapples  | 3

In [76]:
inventory = Table.read_table("inventory.csv")
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

In [78]:
all_different = False
all_different

False

In [79]:
sales = Table.read_table("sales.csv")
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

In [81]:
total_fruits_sold = sum(sales["count sold"])
total_fruits_sold

638

In [84]:
total_revenue = sum(sales["price per fruit ($)"] * sales["count sold"])
total_revenue

106.84999999999999

In [85]:
remaining_inventory = Table.read_table("inventory.csv")
remaining_inventory["count"] = remaining_inventory["count"] - sales["count sold"]
remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23